### ISSUE TITLE
the learning examples (robot and dice) does not stop for several days

### ISSUE THREAD

**Issue by danhlephuoc** [azreasoners/lpmln#1]
Dear authors, 

I have tried the examples like Robot and Dice, but their learning examples do not finish after running for 2-3 days on a very powerful server.

Note that, the simple example in the Readme works fine and very fast. I also tried with the samples at http://reasoning.eas.asu.edu/lpmln/index.html, most of example above worked fine.

**Comment by azreasoners** [comment]
I'm sorry for the late reply and thank you for revealing this issue. 

- The reason why Robot and Dice examples cannot finish is that it takes too long to sample a single stable model for these 2 examples under the default setting while there are 50 iterations and each iteration requires to sample 50 stable models. The process to sample a stable model may even get killed if it takes too long. 

- To resolve this issue, since the observations are complete interpretations, one can add the option "-complete" to decrease the runtime. Besides, since the LPMLN programs for Robot and Dice examples are k-coherent (i.e., every total choice leads to k stable models) for some k, one can also add the option "-kcor" to significantly decrease the runtime. I tested the following commands and they finished within a second. (Please update the file "src/learn_simplelpmln_compevid.py" to the latest version before runing these commands.) 

`python lpmln_learn.py examples/learn/dice.lpmln -o examples/learn/dice.obs -verbosity 10 -complete -kcor`
`python lpmln_learn.py examples/learn/robot.lpmln -o examples/learn/robot.obs -verbosity 10 -complete -kcor`
